pre-release-replacements = [
  {file = "CHANGELOG.md", search = "Unreleased", replace = "{{version}}"},
  {file = "CHANGELOG.md", search = "/commits/HEAD", replace = "/commits/{{tag_name}}", min = 0, max = 1},
  {file = "CHANGELOG.md", search = "\\.\\.\\.HEAD", replace = "...{{tag_name}}", min = 0, max = 1},
  {file = "CHANGELOG.md", search = "ReleaseDate", replace = "{{date}}"},
  {file = "CHANGELOG.md", search = "<!-- next-header -->", replace = "<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly = 1},
  {file = "CHANGELOG.md", search = "<!-- next-url -->", replace = "<!-- next-url -->\n[Unreleased]: https://github.com/gifnksm/rust-template-generated-lib/compare/{{tag_name}}...HEAD", exactly = 1},
  {file = "README.md", search = "rust-template-generated-lib = \"[0-9\\.]+\"", replace = "rust-template-generated-lib = \"{{version}}\""},
  {file = "src/lib.rs", search = "^//! rust-template-generated-lib = \"[0-9\\.]+\"", replace = "//! rust-template-generated-lib = \"{{version}}\""},
  {file = "src/lib.rs", search = "^#!\\[doc\\(html_root_url = \"https://docs.rs/rust-template-generated-lib/[0-9\\.]+\"\\)\\]", replace = "#![doc(html_root_url = \"https://docs.rs/rust-template-generated-lib/{{version}}\")]"},
]
pre-release-hook = ["cargo", "test"]
dev-version = true
