//! Example project generated by gifnksm/rust-tmeplate
//!
//! # Usage
//!
//! Add this to your `Cargo.toml`:
//!
//! ```toml
//! [dependencies]
//! rust-template-generated-lib = "0.2.3"
//! ```

#![doc(html_root_url = "https://docs.rs/rust-template-generated-lib/0.2.3")]

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        let result = 2 + 2;
        assert_eq!(result, 4);
    }
}
