//! Example project generated by gifnksm/rust-tmeplate

#![doc(html_root_url = "https://docs.rs/rust-template-generated-lib/")]

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        let result = 2 + 2;
        assert_eq!(result, 4);
    }
}
